name = "ipvedio"
compatibility_date = "2024-05-10"
main = "src/worker.ts"

[assets]
directory = "dist"
binding = "ASSETS"

[[r2_buckets]]
binding = "vpsai"
bucket_name = "vpsai"

[[kv_namespaces]]
binding = "settings-kv-placeholder"
id = "97cfd9f670854883b6a925db5e31f8dd"
